### ISSUE TITLE
update_nodes not incorporating is_valid 

### ISSUE THREAD

**Issue by dhoogest** [fhcrc/taxtastic#134]
For instance the following yaml fails to upsert node `UW1127`:

```
---
is_valid: false
names:
- is_classified: true
  is_primary: true
  name_class: synonym
  source_name: uw
  tax_id: UW1127
  tax_name: Lactobacillus rhamnosus or Lactobacillus casei
parent_id: '655183'
rank: species
source_name: uw
tax_id: UW1127
type: node
```
